# Generated by Django 2.2.4 on 2019-09-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ip_ad', models.GenericIPAddressField(primary_key=True, protocol='IPv4', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Uploaded_photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_ad', models.ImageField(upload_to='img')),
                ('photo_tag', models.ManyToManyField(to='MAGA.Tag')),
                ('user', models.ForeignKey(on_delete='set null', to='MAGA.User')),
            ],
        ),
    ]
