# Generated by Django 2.2.4 on 2019-09-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAGA', '0003_auto_20190912_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMG',
        ),
    ]
