# Generated by Django 2.2.4 on 2019-09-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MAGA', '0004_delete_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_ad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Uploaded_photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_ad', models.ImageField(upload_to='img')),
                ('photo_tag', models.ManyToManyField(to='MAGA.Tag')),
            ],
        ),
    ]
