# Generated by Django 2.2.4 on 2019-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAGA', '0005_tag_uploaded_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_photo',
            name='photo_ad',
            field=models.ImageField(default='01.png', upload_to='static/upload'),
        ),
    ]
