# Generated by Django 2.2.4 on 2019-09-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAGA', '0009_auto_20190912_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='discription',
            new_name='description',
        ),
    ]
