# Generated by Django 2.2.4 on 2019-09-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAGA', '0010_auto_20190912_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip_ad',
            field=models.GenericIPAddressField(),
        ),
    ]
